export const FOLDER_LIST_REQUEST = 'FOLDER_LIST_REQUEST';
export const FOLDER_LIST_SUCCESS = 'FOLDER_LIST_SUCCESS';
export const FOLDER_LIST_FAIL = 'FOLDER_LIST_FAIL';

export const FOLDER_CREATE_REQUEST = 'FOLDER_CREATE_REQUEST';
export const FOLDER_CREATE_SUCCESS = 'FOLDER_CREATE_SUCCESS';
export const FOLDER_CREATE_FAIL = 'FOLDER_CREATE_FAIL';
export const FOLDER_CREATE_RESET = 'FOLDER_CREATE_RESET';

export const GET_TASKS_BY_FOLDER_REQUEST = 'GET_TASKS_BY_FOLDER_REQUEST';
export const GET_TASKS_BY_FOLDER_SUCCESS = 'GET_TASKS_BY_FOLDER_SUCCESS';
export const GET_TASKS_BY_FOLDER_FAIL = 'GET_TASKS_BY_FOLDER_FAIL';
